#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Landing-site provisioning for awardley.com (issue #183, ADR-0035).
# Run from the repo root:  bash landing/scripts/setup-wizard.sh
# Values are saved to landing/.env.local and pushed to the Vercel project.

TOTAL_STAGES=11

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LANDING_DIR="$REPO_ROOT/landing"
ENV_FILE="$LANDING_DIR/.env.local"
PROJECT="awardley-landing"
BRANCH="landing-page-183"
WRITTEN_VERCEL=()

# vercel_env NAME VALUE — upsert NAME on the linked Vercel project for
# production and preview. Idempotent via --force.
vercel_env() {
  local name="$1" value="$2" env
  if ! command -v vercel >/dev/null 2>&1; then
    warn "vercel CLI not found; set $name in the dashboard"; SKIPPED+=("vercel env $name"); return 0
  fi
  for env in production preview; do
    if printf '%s' "$value" | (cd "$LANDING_DIR" && vercel env add "$name" "$env" --force >/dev/null 2>&1); then
      :
    else
      warn "could not set $name for $env on Vercel"; SKIPPED+=("vercel env $name ($env)")
      return 0
    fi
  done
  WRITTEN_VERCEL+=("$name")
  printf '  %s✓%s Vercel: %s (production, preview)\n' "$GREEN" "$RESET" "$name"
}

# require ask|ask_secret KEY "Prompt" — re-prompt until the value is non-empty. Enter
# alone must never write an empty value to .env.local or to Vercel.
require() {
  local fn="$1" key="$2" prompt="$3"
  while :; do
    "$fn" "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    warn "$key cannot be empty."
  done
}

banner "Awardley landing site: domains, mail and the waiting list"

# ── 1. Push the branch ─────────────────────────────────────────────────────
stage "Push the branch and open the PR"
say "The CI change touches .github/workflows, which only your token may push."
step "This pushes $BRANCH to origin and opens a PR against main."
if confirm "Push $BRANCH now?"; then
  (cd "$REPO_ROOT" && git push -u origin "$BRANCH")
  (cd "$REPO_ROOT" && gh pr create --fill --base main --head "$BRANCH" 2>/dev/null) || note "PR may already exist; continuing."
else
  SKIPPED+=("push $BRANCH")
fi
pause "Continue?"

# ── 2. Create and link the Vercel project ─────────────────────────────────
stage "Create and link the Vercel project"
say "A second project, separate from the app (ADR-0035). The CLI creates it, connects the"
say "GitHub repo, and sets the root directory to landing/ so builds run from there."
if command -v vercel >/dev/null 2>&1; then
  (cd "$LANDING_DIR" && vercel link --yes --project "$PROJECT") || warn "vercel link failed; run it by hand in landing/"
  if (cd "$LANDING_DIR" && vercel api "/v9/projects/$PROJECT" -X PATCH -F rootDirectory=landing -F framework=nextjs >/dev/null 2>&1); then
    printf '  %s✓%s root directory set to landing\n' "$GREEN" "$RESET"
  else
    warn "could not set the root directory; set it in the dashboard: Settings → General → Root Directory → landing"
    SKIPPED+=("root directory = landing")
  fi
else
  warn "vercel CLI not found. Install it (npm i -g vercel) and re-run."
  SKIPPED+=("vercel link")
fi
open_url "https://vercel.com/dashboard"
step "Open project $PROJECT → Settings → General and confirm Root Directory says  landing."
pause "Root directory confirmed?"

# ── 3. Sanity check the link ───────────────────────────────────────────────
stage "Check the link"
if [[ -f "$LANDING_DIR/.vercel/project.json" ]]; then
  printf '  %s✓%s landing/.vercel/project.json present\n' "$GREEN" "$RESET"
else
  warn "landing/.vercel/project.json missing; the env stages below will not reach Vercel."
fi
pause "Continue?"

# ── 4. Resend API key ──────────────────────────────────────────────────────
stage "Resend API key for the landing site"
say "The waiting list adds contacts, so the key needs Full access, not Sending only."
open_url "https://resend.com/api-keys"
step "Create API Key → Name: $PROJECT → Permission: Full access → Domain: All domains"
step "Copy the key; Resend shows it once."
require ask_secret RESEND_API_KEY "Paste the Resend API key"
write_env RESEND_API_KEY "$RESEND_API_KEY"
vercel_env RESEND_API_KEY "$RESEND_API_KEY"
pause "Continue?"

# ── 5. Resend Audience ─────────────────────────────────────────────────────
stage "Create the waiting-list Audience"
say "The Audience is the waiting list. Updates go out as Broadcasts to it."
open_url "https://resend.com/audiences"
step "Create Audience → Name: Awardley waiting list"
step "Open it and copy the Audience ID (a UUID) from the page header or URL."
require ask RESEND_AUDIENCE_ID "Paste the Audience ID"
write_env RESEND_AUDIENCE_ID "$RESEND_AUDIENCE_ID"
vercel_env RESEND_AUDIENCE_ID "$RESEND_AUDIENCE_ID"
pause "Continue?"

# ── 6. Site secrets ────────────────────────────────────────────────────────
stage "Signing secret, reply-to and site origin"
say "The confirmation link is signed with WAITING_LIST_SECRET. Generated here; nothing to copy."
existing_secret="$(_existing WAITING_LIST_SECRET || true)"
if [[ -n "$existing_secret" ]]; then
  WAITING_LIST_SECRET="$existing_secret"; note "Keeping the existing secret."
else
  WAITING_LIST_SECRET="$(openssl rand -hex 32)"
fi
write_env WAITING_LIST_SECRET "$WAITING_LIST_SECRET"
vercel_env WAITING_LIST_SECRET "$WAITING_LIST_SECRET"
say "Replies to hello@awardley.com land in the mailbox you name here."
require ask REPLY_TO "Reply-to address you read"
write_env REPLY_TO "$REPLY_TO"
vercel_env REPLY_TO "$REPLY_TO"
SITE_ORIGIN="https://awardley.com"
write_env SITE_ORIGIN "$SITE_ORIGIN"
vercel_env SITE_ORIGIN "$SITE_ORIGIN"
pause "Continue?"

# ── 7. Verify awardley.com as a Resend sending domain ──────────────────────
stage "Verify awardley.com in Resend"
say "Marketing mail leaves from hello@awardley.com; the app keeps notify.awardley.com (ADR-0034)."
open_url "https://resend.com/domains"
step "Add Domain → awardley.com → Region: US East (same as notify.awardley.com)."
step "Resend lists DNS records: DKIM (TXT), SPF (TXT + MX). Keep that tab open."
open_url "https://dash.cloudflare.com/?to=/:account/awardley.com/dns/records"
step "Add each record at Cloudflare exactly as shown. Proxy status: DNS only (grey cloud)."
step "Back in Resend, click Verify DNS Records. It can take a few minutes."
warn "Do not remove the existing notify.awardley.com records."
pause "Domain shows Verified?"

# ── 8. Attach the hostnames to the Vercel project ──────────────────────────
stage "Attach awardley.com and www to the project"
open_url "https://vercel.com/dashboard"
step "Open project $PROJECT → Settings → Domains."
step "Add  awardley.com  (this becomes the production domain)."
step "Add  www.awardley.com  and choose Redirect to awardley.com (308)."
step "Vercel now shows the DNS records each hostname needs. Keep that tab open."
pause "Both hostnames added?"

# ── 9. Cloudflare records for the apex and www ─────────────────────────────
stage "Cloudflare records for the apex and www"
say "Use the exact values the Vercel Domains tab shows; they are the source of truth."
open_url "https://dash.cloudflare.com/?to=/:account/awardley.com/dns/records"
step "Apex: add the A record Vercel shows for awardley.com (name @)."
step "www: add the CNAME Vercel shows for www.awardley.com."
step "Both records: Proxy status DNS only (grey cloud). Proxied would need Full (strict) TLS."
step "Back in Vercel, wait for both hostnames to show Valid Configuration."
note "The existing  app  CNAME stays as it is."
pause "Both hostnames valid in Vercel?"

# ── 10. Analytics, BotID and rate limiting ─────────────────────────────────
stage "Web Analytics, BotID and rate limiting"
open_url "https://vercel.com/dashboard"
step "Project $PROJECT → Analytics → Enable. (Cookieless; the privacy page already mentions it.)"
step "BotID basic needs no dashboard toggle; the site calls it in code. Confirm at"
open_url "https://vercel.com/docs/botid"
step "Project → Firewall → Rate Limiting: if the plan offers it, add a rule for POST requests to / at 10 per minute per IP."
note "On a plan without rate limiting, BotID plus the honeypot and double opt-in are the floor (spec on #183)."
pause "Done here?"

# ── 11. Merge and verify ───────────────────────────────────────────────────
stage "Merge the PR and verify"
say "Merging main triggers the production deploy of the landing site."
step "Merge the PR for $BRANCH."
open_url "https://awardley.com"
step "Confirm the page loads over HTTPS, in both languages, and https://www.awardley.com redirects."
step "Join the waiting list with your own address. The confirmation email should arrive from hello@awardley.com."
step "Click the link; the page should say you are on the list."
open_url "https://resend.com/audiences"
step "Your address should now be a contact in the Audience."
pause "All verified?"

finish
if ((${#WRITTEN_VERCEL[@]})); then
  printf '  Vercel variables set: %s\n' "${WRITTEN_VERCEL[*]}"
fi
